export enum UserRole {
  SUPER_ADMIN = 'SUPER_ADMIN', // <-- ADD THIS LINE
  ADMIN = 'ADMIN',
  VENDOR = 'VENDOR',
  CUSTOMER = 'CUSTOMER',
  GUEST = 'GUEST',
  DELIVERER = 'DELIVERER',
  POS_MANAGER = 'POS_MANAGER',
  POS_OPERATOR = 'POS_OPERATOR',
  SUPPLIER_ACCOUNT = 'SUPPLIER_ACCOUNT',
  B2B_BUYER = 'B2B_BUYER',
}
